DROP TABLE EQUIPAMENTO;


CREATE TABLE EQUIPAMENTO
(
    IDENTIFICADOR NUMBER(9),
    DATA_AQUISICAO DATE,
    DESCRICAO VARCHAR(100),
    CUSTO_DIARIA NUMBER(10),
    PRIMARY KEY (IDENTIFICADOR)
);



insert into EQUIPAMENTO (IDENTIFICADOR,DATA_AQUISICAO,DESCRICAO,CUSTO_DIARIA) 
select 333, TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'T', 23444 from dual
union all select 444, TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'T', 23444 from dual;

SELECT  * FROM EQUIPAMENTO ORDER BY DESCRICAO;
SELECT * FROM EQUIPAMENTO WHERE DESCRICAO = 'M';



