DROP TABLE FUNCIONARIO;


CREATE TABLE FUNCIONARIO
(
    MATRICULA NUMBER(9),
    SENHA VARCHAR(20),
    NASCIMENTO DATE,
    DATA_ADMISSAO DATE,
    SEXO VARCHAR(1),
    NOME VARCHAR(35),
    ENDERECO VARCHAR(35),
    SALARIO NUMBER(5),
    PRIMARY KEY (MATRICULA)
    
);



insert into FUNCIONARIO (MATRICULA,SENHA,NASCIMENTO,DATA_ADMISSAO,SEXO,NOME,ENDERECO,SALARIO)
select 123456389, '8734hrr', TO_DATE('07-JAN-56'), TO_DATE('07-JAN-99'),'M','ANTONIO', 'Rua Paulo', 10000 from dual
union all select 123456789, 'hf27834', TO_DATE('07-JAN-66'), TO_DATE('07-JAN-03'),'M','JOSE', 'Rua Julio', 5000 from dual;


SELECT * FROM FUNCIONARIO ORDER BY NOME;

SELECT * FROM FUNCIONARIO WHERE NOME = 'ANTONIO';


