SELECT *  FROM CIDADES;


SELECT * FROM CIDADES WHERE UF = 'SP';


SELECT * FROM USUARIOS 
JOIN CLIENTES ON USUARIOS.COD_USUARIO = CLIENTES.COD_CLIENTE
JOIN TELEFONES ON CLIENTES.COD_CLIENTE = TELEFONES.COD_CLIENTE
WHERE TELEFONES.DDD = 21;




